framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache__ToDELETE keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache__ToDELETE stores to the filesystem by default.
        # The data in this cache__ToDELETE should persist between deploys.
        # Other options include:

        # Redis
        #app: cache__ToDELETE.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache__ToDELETE.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache__ToDELETE: null
