version: '3.1'

services:

  adminer:
    image: adminer
    ports:
      - "8000:8080"
    networks:
      - default

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    env_file: .env.local
    
    ports:
      - "5432:5432"
    
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - default

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###

networks:
  default:
    driver: bridge
